version: '2'
services:
  web:
    image: 'uazlibraries/nginx-shibboleth'
    restart: always
    tty: true
    links:
      - fpm
    ports:
      - "80:80"
    environment:
      - FILESENDER_DOMAIN=localhost

    volumes:
      - run.php:/run/php
      - run.shibboleth:/run/shibboleth
      - filesender:/opt/filesender
      - simplesaml:/opt/simplesamlphp
      - ./nginx/conf.d:/etc/nginx/conf.d

  fpm:
    image: 'filesender-phpfpm'
    restart: always
    links:
      - db-host
    environment:
      - SMTP_SERVER=smtpgate.mail.arizona.edu
      - FILESENDER_DOMAIN=localhost
      - DB_HOST=db-host
      - DB_NAME=filesender
      - DB_USER=filesender
      - DB_PASSWORD=filesender
      - CHOWN_WWW=333
    volumes:
      - run.php:/run/php
      - filesender:/opt/filesender
      - simplesaml:/opt/simplesamlphp

  shib:
    image: 'uazlibraries/shibboleth-fastcgi'
    restart: always
    volumes:
      - ./shibboleth:/etc/shibboleth
      - run.shibboleth:/run/shibboleth

  db-host:
    image: 'mysql'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=insecure
      - MYSQL_DATABASE=filesender
      - MYSQL_USER=filesender
      - MYSQL_PASSWORD=filesender
      - MYSQL_ALLOW_EMPTY_PASSWORD='false'

volumes:
  run.php:
  run.shibboleth:
  filesender:
  simplesaml:
