version: '2'
services:
  web:
    image: 'uazlibraries/nginx-shibboleth'
    restart: always
    tty: true
    links:
      - fpm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - run.php:/run/php
      - run.shibboleth:/run/shibboleth
      - filesender:/opt/filesender
      - simplesaml:/opt/simplesamlphp
      - ./shibboleth:/etc/shibboleth
      - ./nginx/conf.d:/etc/nginx/conf.d

  fpm:
    image: 'uazlibraries/filesender-phpfpm:2.0-beta3'
    restart: always
    links:
      - db-host
    environment:
      - SMTP_SERVER=smtp.gmail.com:587
      - SMTP_TLS=true
      - SMTP_USER=dockertestfilesender
      - SMTP_PSWD=thisisalongpassword
      - ADMIN_EMAIL=dockertestfilesender@gmail.com
      - ADMIN_PSWD=password
      - FILESENDER_URL=https://{PUBLICIP}
      - FILESENDER_AUTHTYPE=shibboleth
      - MAIL_ATTR=EPPN
      - NAME_ATTR=EPPN
      - UID_ATTR=EPPN
      - DB_HOST=db-host
      - DB_NAME=filesender
      - DB_USER=filesender
      - DB_PASSWORD=filesender
      - CHOWN_WWW=33
    volumes:
      - run.php:/run/php
      - filesender:/opt/filesender
      - simplesaml:/opt/simplesamlphp

  shib:
    image: 'uazlibraries/shibboleth-fastcgi'
    restart: always
    volumes:
      - ./shibboleth:/etc/shibboleth
      - run.shibboleth:/run/shibboleth

  db-host:
    image: 'mysql'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=insecure
      - MYSQL_DATABASE=filesender
      - MYSQL_USER=filesender
      - MYSQL_PASSWORD=filesender
      - MYSQL_ALLOW_EMPTY_PASSWORD='false'

volumes:
  run.php:
  run.shibboleth:
  filesender:
  simplesaml:
