version: '2'
services:
  web:
    build: ./web
    restart: always
    tty: true
    links:
      - fpm
      - selenium
    ports:
      - "80:80"
    volumes:
      - run.php:/run/php
      - ./filesender:/opt/filesender
      - simplesaml:/opt/simplesamlphp
      - ./nginx/conf.d:/etc/nginx/conf.d

  fpm:
    image: 'uazlibraries/filesender-phpfpm:devel'
    restart: always
    links:
      - db-host
      - selenium
    environment:
      - SMTP_SERVER=smtp.gmail.com:587
      - SMTP_TLS=true
      - SMTP_USER=dockertestfilesender
      - SMTP_PSWD=thisisalongpassword
      - ADMIN_EMAIL=dockertestfilesender@gmail.com
      - ADMIN_PSWD=password
      - CHOWN_WWW=1000:1000
      - FILESENDER_URL=http://localhost/upload
      - FILESENDER_LOGOUT_URL=http://localhost
      - FILESENDER_STORAGE=FilesystemPreserveName
      - FILESENDER_AUTHTYPE=saml
      - FILESENDER_AUTHSAML=static-user
      - SELENIUM_HOST=http://localhost:4444/wd/hub
      - DB_HOST=db-host
      - DB_TYPE=pgsql
      - DB_NAME=filesender
      - DB_USER=postgres
      - DB_PASSWORD=password
    volumes:
      - run.php:/run/php
      - ./filesender:/opt/filesender
      - simplesaml:/opt/simplesamlphp
      - ./simplesamlphp/config/authsources.php:/opt/simplesamlphp/config/authsources.php

  selenium:
    image: 'selenium/standalone-chrome-debug:3.11.0-dysprosium'
    restart: always
    ports:
      - "4444:4444"
      - "5999:5900"
    volumes:
      - /dev/shm:/dev/shm

  db-host:
    image: 'postgres:10.3'
    restart: always
    environment:
      - POSTGRES_DB=filesender
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

volumes:
  run.php:
  simplesaml:

#    image: 'selenium/standalone-firefox:2.53.0'
