version: '2'
services:
  web:
    build: ./web
    restart: always
    tty: true
    links:
      - fpm
    ports:
      - "80:80"
    volumes:
      - run.php:/run/php
      - ./filesender:/opt/filesender
      - simplesaml:/opt/simplesamlphp
      - ./nginx/conf.d:/etc/nginx/conf.d

  fpm:
    image: 'uazlibraries/filesender-phpfpm:devel'
    restart: always
    links:
      - db-host
    environment:
      - SMTP_SERVER=smtp.gmail.com:587
      - SMTP_TLS=true
      - SMTP_USER=dockertestfilesender
      - SMTP_PSWD=thisisalongpassword
      - ADMIN_EMAIL=dockertestfilesender@gmail.com
      - ADMIN_PSWD=password
      - CHOWN_WWW=1000:1000
      - FILESENDER_URL=http://localhost/upload
      - FILESENDER_LOGOUT_URL=http://localhost
      - FILESENDER_STORAGE=FilesystemPreserveName
      - FILESENDER_AUTHTYPE=saml
      - FILESENDER_AUTHSAML=static-user
      - DB_HOST=db-host
      - DB_TYPE=pgsql
      - DB_NAME=filesender
      - DB_USER=filesender
      - DB_PASSWORD=filesender
    volumes:
      - run.php:/run/php
      - ./filesender:/opt/filesender
      - simplesaml:/opt/simplesamlphp
      - ./simplesamlphp/config/authsources.php:/opt/simplesamlphp/config/authsources.php

  db-host:
    image: 'postgres:10.3'
    restart: always
    environment:
      - POSTGRES_DB=filesender
      - POSTGRES_USER=filesender
      - POSTGRES_PASSWORD=filesender

volumes:
  run.php:
  simplesaml:
