apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: db-host
  name: db-host
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db-host
    spec:
      containers:
      - env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: '''false'''
        - name: MYSQL_DATABASE
          value: filesender
        - name: MYSQL_PASSWORD
          value: filesender
        - name: MYSQL_ROOT_PASSWORD
          value: insecure
        - name: MYSQL_USER
          value: filesender
        image: mysql
        name: db-host
        resources: {}
      restartPolicy: Always
status: {}
